decks.push(
{
  name: 'k.5',
  description: 'Vocabulary',
  cards: [
  	{source: "der Ạnwalt", target: "lawyer", plural: "der Ạnwalt"},
		{source: "die Ạnwältin", target: "lawyer", plural: "die Ạnwältinen"},
		{source: "der Ạrzt", target: "physician, doctor", plural: "der Ạrzt"},
		{source: "die Ärztin", target: "physician, doctor", plural: "die Ärztinen"},
		{source: "der Bademeister", target: "swimming-pool attendant", plural: "der Bademeister"},
		{source: "die Bademeisterin", target: "swimming-pool attendant", plural: "die Bademeisterinen"},
		{source: "der Bạnkangestellte", target: "bank employee", plural: "der Bạnkangestellten"},
		{source: "die Bạnkangestellte", target: "bank employee", plural: "die Bạnkangestellten"},
		{source: "der Bauarbeiter", target: "construction worker", plural: "der Bauarbeiter"},
		{source: "die Bauarbeiterin", target: "construction worker", plural: "die Bauarbeiterinen"},
		{source: "der Berufsberater", target: "career counselor", plural: "der Berufsberater"},
		{source: "die Berufsberaterin", target: "career counselor", plural: "die Berufsberaterinen"},
		{source: "der Dirigẹnt", target: "(orchestra) conductor", plural: "der Dirigẹnt"},
		{source: "die Dirigẹntin", target: "(orchestra) conductor", plural: "die Dirigẹntinen"},
		{source: "der Friseur", target: "hairdresser", plural: "der Friseur"},
		{source: "die Friseurin", target: "hairdresser", plural: "die Friseurinen"},
		{source: "der Hausmeister", target: "custodian", plural: "der Hausmeister"},
		{source: "die Hausmeisterin", target: "custodian", plural: "die Hausmeisterinen"},
		{source: "der Krạnkenpfleger", target: "nurse", plural: "der Krạnkenpfleger"},
		{source: "die Krạnkenpflegerin", target: "nurse", plural: "die Krạnkenpflegerinen"},
		{source: "der Rịchter", target: "judge", plural: "der Rịchter"},
		{source: "die Rịchterin", target: "judge", plural: "die Rịchterinen"},
		{source: "der Schrịftsteller", target: "writer", plural: "der Schrịftsteller"},
		{source: "die Schrịftstellerin", target: "writer", plural: "die Schrịftstellerinen"},
		{source: "der Verkäufer", target: "salesperson", plural: "der Verkäufer"},
		{source: "die Verkäuferin", target: "salesperson", plural: "die Verkäuferinen"},
		{source: "die Ẹcke", target: "corner", plural: "die Ẹcken"},
		{source: "um die Ẹcke", target: "around the corner", plural: "um die Ẹcke"},
		{source: "die Fabrik", target: "factory", plural: "die Fabriken"},
		{source: "in der Fabrik", target: "in the factory", plural: "in der Fabrik"},
		{source: "die Gạststätte", target: "restaurant", plural: "die Gạststätten"},
		{source: "in der Gạststätte", target: "at the restaurant", plural: "in der Gạststätte"},
		{source: "die Kạsse", target: "ticket booth", plural: "die Kạssen"},
		{source: "an der Kạsse", target: "at the ticket booth", plural: "an der Kạsse"},
		{source: "die Kịrche", target: "church", plural: "die Kịrchen"},
		{source: "in der Kịrche", target: "at church", plural: "in der Kịrche"},
		{source: "die Polizei", target: "police station", plural: "die Polizei"},
		{source: "auf der Polizei", target: "at the police station", plural: "auf der Polizei"},
		{source: "die Pọst", target: "post office", plural: "die Pọst"},
		{source: "auf der Pọst", target: "at the post office", plural: "auf der Pọst"},
		{source: "die Tạnkstelle", target: "gas station", plural: "die Tạnkstellen"},
		{source: "an der Tạnkstelle", target: "at the gas station", plural: "an der Tạnkstelle"},
		{source: "der Bahnhof,", target: "train station", plural: "der Bahnhof,"},
		{source: "auf dem Bahnhof", target: "at the train station", plural: "auf dem Bahnhof"},
		{source: "der Schạlter", target: "ticket booth", plural: "der Schạlter"},
		{source: "am Schạlter", target: "at the ticket booth", plural: "am Schạlter"},
		{source: "das Büro", target: "office", plural: "das Büros"},
		{source: "im Büro", target: "at the office", plural: "im Büro"},
		{source: "das Gerịcht", target: "courthouse", plural: "das Gerịchte"},
		{source: "auf dem Gerịcht", target: "at the courthouse", plural: "auf dem Gerịcht"},
		{source: "das Kaufhaus,", target: "department store", plural: "das Kaufhaus,"},
		{source: "im Kaufhaus", target: "at the department store", plural: "im Kaufhaus"},
		{source: "das Krạnkenhaus,", target: "hospital", plural: "das Krạnkenhaus,"},
		{source: "im Krạnkenhaus", target: "in the hospital", plural: "im Krạnkenhaus"},
		{source: "das Schwịmmbad,", target: "swimming pool", plural: "das Schwịmmbad,"},
		{source: "im Schwịmmbad", target: "at the swimming pool", plural: "im Schwịmmbad"},
		{source: "die Fẹnsterbank", target: "windowsill", plural: "die Fẹnsterbank"},
		{source: "die Flạsche", target: "bottle", plural: "die Flạschen"},
		{source: "die Küche", target: "kitchen", plural: "die Küchen"},
		{source: "die Küchenwaage", target: "kitchen scale", plural: "die Küchenwaagen"},
		{source: "die Salatschüssel", target: "salad (mixing) bowl", plural: "die Salatschüsseln"},
		{source: "die Schublade", target: "drawer", plural: "die Schubladen"},
		{source: "die Tạsse", target: "cup", plural: "die Tạssen"},
		{source: "der Bạckofen", target: "oven", plural: "der Bạckofen"},
		{source: "der Geschịrrspüler", target: "dishwasher", plural: "der Geschịrrspüler"},
		{source: "der Herd", target: "stove", plural: "der Herde"},
		{source: "der Kühlschrank", target: "refrigerator", plural: "der Kühlschrank"},
		{source: "der Tọpf", target: "pot, pan", plural: "der Tọpf"},
		{source: "der Tọpflappen", target: "potholder", plural: "der Tọpflappen"},
		{source: "der Wạsserhahn", target: "faucet", plural: "der Wạsserhahn"},
		{source: "das Bestẹck", target: "silverware, cutlery", plural: "das Bestẹck"},
		{source: "das Geschịrr", target: "dishes", plural: "das Geschịrr"},
		{source: "das Papiertuch", target: "paper towel", plural: "das Papiertuch"},
		{source: "das Spülbecken", target: "sink", plural: "das Spülbecken"},
		{source: "die Badehose", target: "swim(ming) trunks", plural: "die Badehosen"},
		{source: "die Briefmarke", target: "stamp", plural: "die Briefmarken"},
		{source: "die Hạlskette", target: "necklace", plural: "die Hạlsketten"},
		{source: "die Mütze", target: "cap", plural: "die Mützen"},
		{source: "der Regenschirm", target: "umbrella", plural: "der Regenschirme"},
		{source: "der Reiseführer", target: "travel guidebook", plural: "der Reiseführer"},
		{source: "der Roman", target: "novel", plural: "der Romane"},
		{source: "das Weihnachtsgeschenk", target: "Christmas present", plural: "das Weihnachtsgeschenke"},
		{source: "die Ausbildung prạktische Ausbildung", target: "specialized training practical (career) training", plural: "die Ausbildung prạktische Ausbildung"},
		{source: "die Bụndeswehr bei der Bụndeswehr", target: "German army in the German army", plural: "die Bụndeswehr bei der Bụndeswehr"},
		{source: "die Schulbildung", target: "education, schooling", plural: "die Schulbildung"},
		{source: "die Dusche", target: "shower", plural: "die Duschen"},
		{source: "die Eintrittskarte", target: "admissions ticket", plural: "die Eintrittskarten"},
		{source: "die Ẹnkelin", target: "granddaughter", plural: "die Ẹnkelinen"},
		{source: "die Frẹmdsprache", target: "foreign language", plural: "die Frẹmdsprachen"},
		{source: "die Lehre", target: "apprenticeship", plural: "die Lehren"},
		{source: "die Lieblingsbeschäfti-gung", target: "favorite activity", plural: "die Lieblingsbeschäfti-gungen"},
		{source: "die Möglichkeit", target: "possibility", plural: "die Möglichkeiten"},
		{source: "die Umkleidekabine", target: "dressing room", plural: "die Umkleidekabinen"},
		{source: "die Versịcherung", target: "insurance", plural: "die Versịcherungen"},
		{source: "die Wẹrkstatt", target: "repair shop, garage", plural: "die Wẹrkstatt"},
		{source: "der Ẹnkel", target: "grandson", plural: "der Ẹnkel"},
		{source: "der Kuchen", target: "cake", plural: "der Kuchen"},
		{source: "der Rasen", target: "lawn", plural: "der Rasen"},
		{source: "der Rat, Ratschläge", target: "advice", plural: "der Rat, Ratschläge"},
		{source: "der Schweinestall", target: "pigpen", plural: "der Schweinestall"},
		{source: "der Termin", target: "appointment", plural: "der Termine"},
		{source: "der Urlaub", target: "vacation", plural: "der Urlaube"},
		{source: "der Vorschlag", target: "suggestion", plural: "der Vorschlag"},
		{source: "das Bauernbrot", target: "(loaf of) farmer's bread", plural: "das Bauernbrote"},
		{source: "das Dọppelzimmer", target: "double room", plural: "das Dọppelzimmer"},
		{source: "das Geheimnis", target: "secret", plural: "das Geheimnisse"},
		{source: "das Hụndefutter", target: "dog food", plural: "das Hụndefutter"},
		{source: "das Interẹsse", target: "interest", plural: "das Interẹssen"},
		{source: "Interẹsse haben an (+ dat.)", target: "to be interested in", plural: "Interẹsse haben an (+ dat.)"},
		{source: "das Kọnto, Kọnten", target: "bank account", plural: "das Kọnto, Kọnten"},
		{source: "ein Kọnto eröffnen", target: "to open a bank account", plural: "ein Kọnto eröffnen"},
		{source: "das Lieblingsfach", target: "favorite subject", plural: "das Lieblingsfach"},
		{source: "das Öl", target: "oil", plural: "das Öl"},
		{source: "das Öl kontrollieren", target: "to check the oil", plural: "das Öl kontrollieren"},
		{source: "die Kẹnntnisse (pl.)", target: "skills; knowledge about a field", plural: "die Kẹnntnisse (pl.)"},
		{source: "aus·tragen, trägt …", target: "to deliver", plural: "aus·tragen, trägt …"},
		{source: "Zeitungen austragen", target: "to deliver newspapers", plural: "Zeitungen austragen"},
		{source: "dẹcken", target: "to cover; set", plural: "dẹcken"},
		{source: "den Tịsch decken", target: "to set the table", plural: "den Tịsch decken"},
		{source: "ein·kaufen gehen, ist", target: "to go shopping", plural: "ein·kaufen gehen, ist"},
		{source: "erklären", target: "to explain", plural: "erklären"},
		{source: "erzählen", target: "to tell (a story, joke)", plural: "erzählen"},
		{source: "fegen", target: "to sweep", plural: "fegen"},
		{source: "feiern", target: "to celebrate", plural: "feiern"},
		{source: "heiraten", target: "to marry", plural: "heiraten"},
		{source: "interessieren", target: "to interest", plural: "interessieren"},
		{source: "sich interessieren für", target: "to be interested in", plural: "sich interessieren für"},
		{source: "leid·tun, leidgetan (+ dat.)", target: "to be sorry", plural: "leid·tun, leidgetan (+ dat.)"},
		{source: "tut mir leid", target: "I'm sorry", plural: "tut mir leid"},
		{source: "leihen, geliehen", target: "to lend", plural: "leihen, geliehen"},
		{source: "mähen", target: "to mow", plural: "mähen"},
		{source: "pflegen", target: "to attend to; to nurse", plural: "pflegen"},
		{source: "sagen", target: "to say, tell", plural: "sagen"},
		{source: "schẹnken", target: "to give (as a present)", plural: "schẹnken"},
		{source: "stạtt·finden, stạttgefunden", target: "to take place", plural: "stạtt·finden, stạttgefunden"},
		{source: "stẹllen", target: "to place, put", plural: "stẹllen"},
		{source: "eine Frage stellen", target: "to ask a question", plural: "eine Frage stellen"},
		{source: "unterrịchten", target: "to teach, instruct", plural: "unterrịchten"},
		{source: "untersuchen", target: "to investigate; to examine", plural: "untersuchen"},
		{source: "verkaufen", target: "to sell", plural: "verkaufen"},
		{source: "vọll·tanken", target: "to fill up (with gas)", plural: "vọll·tanken"},
		{source: "wẹg·stellen", target: "to put away", plural: "wẹg·stellen"},
		{source: "werden, wịrd, ist gewọrden", target: "to become", plural: "werden, wịrd, ist gewọrden"},
		{source: "zahlen", target: "to pay", plural: "zahlen"},
		{source: "zeichnen", target: "to draw", plural: "zeichnen"},
		{source: "Adjektive und Adverbien", target: "Adjectives and Adverbs", plural: "Adjektive und Adverbien"},
		{source: "ausverkauft", target: "sold out", plural: "ausverkauft"},
		{source: "dụnkel", target: "dark", plural: "dụnkel"},
		{source: "getrẹnnt", target: "separately; separate checks", plural: "getrẹnnt"},
		{source: "leer", target: "empty", plural: "leer"},
		{source: "sauer", target: "angry", plural: "sauer"},
		{source: "unglaublich", target: "incredible", plural: "unglaublich"},
		{source: "ạls", target: "as; when", plural: "ạls"},
		{source: "als wạs?", target: "as what?", plural: "als wạs?"},
		{source: "als ich ạcht Jahre alt", target: "when I was eight years", plural: "als ich ạcht Jahre alt"},
		{source: "war", target: "old", plural: "war"},
		{source: "ẹtwas", target: "something, anything", plural: "ẹtwas"},
		{source: "sọnst noch etwas?", target: "anything else?", plural: "sọnst noch etwas?"},
		{source: "fạst", target: "almost", plural: "fạst"},
		{source: "gẹrn", target: "gladly", plural: "gẹrn"},
		{source: "ich möchte gern", target: "I would like", plural: "ich möchte gern"},
		{source: "hịn und ", target: "round-trip", plural: "hịn und "},
		{source: "jede, jeder, jedes", target: "each", plural: "jede, jeder, jedes"},
		{source: "mehrmals", target: "several times", plural: "mehrmals"},
		{source: "nebenạn", target: "next door", plural: "nebenạn"},
		{source: "von nebenạn", target: "from next door", plural: "von nebenạn"},
		{source: "sọnst", target: "otherwise", plural: "sọnst"},
		{source: "ụ nter", target: "under, underneath", plural: "ụ nter"},
		{source: "unter dem Fẹnster", target: "under the window", plural: "unter dem Fẹnster"},
		{source: "wem", target: "whom (dative)", plural: "wem"},
		{source: "zweimal", target: "twice", plural: "zweimal"}
  ]
});