decks.push(
{
  name: 'k.6',
  description: 'Vocabulary',
  cards: [
  	{source: "die Apotheke", target: "pharmacy"},
		{source: "die Drogerie", target: "drugstore"},
		{source: "die Metzgerei", target: "butcher shop"},
		{source: "die Reinigung", target: "dry cleaners"},
		{source: "die Stadt", target: "town, city"},
		{source: "die Heimatstadt", target: "hometown"},
		{source: "die Innenstadt", target: "downtown"},
		{source: "die Straße", target: "street, road"},
		{source: "der Flughafen", target: "airport"},
		{source: "der Stadtrand", target: "city limits"},
		{source: "der Stadtteil", target: "district, neighborhood"},
		{source: "das Eisenwarengeschäft", target: "hardware store"},
		{source: "das Gefängnis", target: "prison, jail"},
		{source: "das Gymnasium", target: "high school, college"},
		{source: "Gymnasien", target: "preparatory school"},
		{source: "das Rathaus", target: "town hall"},
		{source: "das Schreibwarengeschäft", target: "stationery store"},
		{source: "das Stadtviertel", target: "district, neighborhood"},
		{source: "die Badewanne", target: "bathtub"},
		{source: "die Treppe", target: "stairway"},
		{source: "die Zentralheizung", target: "central heating"},
		{source: "der Aufzug", target: "elevator"},
		{source: "der Ausblick", target: "view"},
		{source: "der Quadratmeter (qm)", target: "square meter (m2)"},
		{source: "der Stock", target: "floor, story on the second floor"},
		{source: "das Dach", target: "roof"},
		{source: "das Waschbecken", target: "(wash)basin"},
		{source: "die Bürste", target: "brush"},
		{source: "die Gießkanne", target: "watering can"},
		{source: "die Kommode", target: "dresser"},
		{source: "der Besen", target: "broom"},
		{source: "der Frühjahrsputz", target: "spring cleaning"},
		{source: "der Gartenschlauch", target: "garden hose"},
		{source: "der trash", target: "garbage"},
		{source: "der Putzlappen", target: "cloth, rag (for cleaning)"},
		{source: "der Rasenmäher", target: "lawn mower"},
		{source: "der Schrank", target: "closet; cupboard"},
		{source: "der Kleiderschrank", target: "clothes closet, wardrobe"},
		{source: "der Sessel", target: "armchair"},
		{source: "der Spiegel", target: "mirror"},
		{source: "der Staubsauger", target: "vacuum cleaner"},
		{source: "der Vorhang", target: "drapery, curtain"},
		{source: "das Bügeleisen", target: "iron"},
		{source: "das Kopfkissen", target: "pillow"},
		{source: "die Möbel", target: "furniture"},
		{source: "Wohnmöglichkeiten", target: "Living Arrangements"},
		{source: "die Skihütte", target: "ski lodge"},
		{source: "die Villa", target: "mansion"},
		{source: "die Wohngemeinschaft", target: "shared housing"},
		{source: "das Haus", target: "house"},
		{source: "das Bauernhaus", target: "farmhouse"},
		{source: "das Einfamilienhaus", target: "single-family home"},
		{source: "das Hochhaus", target: "high-rise building"},
		{source: "das Reihenhaus", target: "row house, town house"},
		{source: "die A. nzeige", target: "ad"},
		{source: "die Miete", target: "rent"},
		{source: "die Mieterin", target: "female renter"},
		{source: "die Suchanzeige", target: "housing-wanted ad"},
		{source: "die Vermieterin", target: "landlady"},
		{source: "der Mieter", target: "male renter"},
		{source: "der Vermieter", target: "landlord"},
		{source: "die Nebenkosten (pl.)", target: "extra costs"},
		{source: "Sonstige Substantive", target: "Other Nouns"},
		{source: "die Nähe", target: "vicinity"},
		{source: "in der Nähe", target: "in the vicinity"},
		{source: "die Seite", target: "side; page"},
		{source: "die Tätigkeit", target: "activity"},
		{source: "die Zugfahrkarte", target: "train ticket"},
		{source: "das Ausland", target: "foreign countries"},
		{source: "im Ausland", target: "foreign countries abroad"},
		{source: "das Benzin", target: "gasoline"},
		{source: "das Land", target: "country (rural)"},
		{source: "auf dem Land", target: "in the country"},
		{source: "Verben", target: "Verbs"},
		{source: "abtrocknen", target: "to dry (dishes)"},
		{source: "begegnen (+ dat.)", target: "to meet"},
		{source: "bügeln", target: "to iron"},
		{source: "fehlen (+ dat.)", target: "to be missing"},
		{source: "geben", target: "to give"},
		{source: "es gibt …", target: "there is/are …"},
		{source: "gibt es …? (R)", target: "is/are there …?"},
		{source: "gefallen", target: "to be to one's liking, to please"},
		{source: "es mir", target: "I like it"},
		{source: "gehören (+ dat.)", target: "to belong to"},
		{source: "gratulieren (+ dat.)", target: "to congratulate"},
		{source: "helfen", target: "to help"},
		{source: "mieten", target: "to rent"},
		{source: "passen (+ dat.)", target: "to fit"},
		{source: "putzen", target: "to clean"},
		{source: "schaden (+ dat.)", target: "to be harmful to"},
		{source: "schmecken (+ dat.)", target: "to taste good to"},
		{source: "Staub saugen", target: "to vacuum"},
		{source: "stehen", target: "to stand"},
		{source: "stehen", target: "to suit"},
		{source: "tippen", target: "to type"},
		{source: "übernachten", target: "to stay overnight"},
		{source: "vermieten", target: "to rent out"},
		{source: "vorstellen  to introduce", target: "present"},
		{source: "sich etwas vorstellen", target: "to imagine something"},
		{source: "wiederholen", target: "to repeat"},
		{source: "wischen", target: "to mop"},
		{source: "abwischen", target: "to wipe clean"},
		{source: "zuhören", target: "to listen to"},
		{source: "angenehm", target: "pleasant"},
		{source: "eigen", target: "own"},
		{source: "hell", target: "light"},
		{source: "möbliert", target: "furnished"},
		{source: "warm", target: "heated, heat included"},
		{source: "weit", target: "far"},
		{source: "Wie weit weg?", target: "How far away?"},
		{source: "wunderschön", target: "exceedingly beautiful"},
		{source: "auf Wiederhören", target: "good bye"},
		{source: "bei", target: "at; with"},
		{source: "bei deinen Ẹltern", target: "with/at your parents'"},
		{source: "bei einer Bank", target: "at a bank"},
		{source: "Ist ein/eine … dabei?", target: "Does it come with a …?"},
		{source: "drin/darin", target: "in it"},
		{source: "egal", target: "equal, same"},
		{source: "Das ist mir egal.", target: "It doesn't matter to me"},
		{source: "gegenüber", target: "opposite; across"},
		{source: "gleich gegenüber", target: "right across the way"},
		{source: "gleich right away; right", target: "directly"},
		{source: "gleich um die Ẹcke", target: "right around the corner"},
		{source: "inklusive", target: "included (utilities)"},
		{source: "möglichst (+ adverb)", target: "as … as possible"},
		{source: "ob", target: "if, whether"},
		{source: "prima!", target: "great!"},
		{source: "schade!", target: "too bad!"},
		{source: "unter (R)", target: "below, beneath; among"},
		{source: "wegen", target: "on account of; about"}
  ]
});